### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by Linuturk** [Linuturk/salt.faucet.io#9]

**Comment by UserNameless** [comment]
Tracking ID
UA-58446085-1


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-58446085-1', 'auto');
  ga('send', 'pageview');

</script>


PHP Implementationoptional

Create a PHP file named "analyticstracking.php" with the code above and include it on each PHP template page. Then, add the following line to each template page immediately after the opening <body> tag:
<?php include_once("analyticstracking.php") ?>

**Comment by UserNameless** [comment]
I tried to add in the script...  but it didn't display.  I'll email it in a bit, and worry about formatting here later.

**Comment by Linuturk** [comment]
Received and added to the development application. Thanks!

**Comment by Linuturk** [comment]
I've added the analytics code to the application repository.
